include:
 - project: fsl/fsl-ci-rules
   file:    .gitlab-ci.yml

stages:
  - Static Analysis
  - Test
  - doc
  - fsl-ci-pre
  - fsl-ci-build
  - fsl-ci-deploy

flake8:
  image: python:3.7-slim-buster
  stage: Static Analysis
  before_script:
  - python --version
  - pip install flake8  
  script:
  - flake8 --max-line-length=120 fsl_mrs
  allow_failure: true

pytest:
  image: wtclarke/fsl_mrs_tests:1.0
  stage: Test
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
  - conda init bash
  - source ~/.bashrc 
  - conda create -n fsl_mrs -y python=3.7
  - conda activate fsl_mrs
  - conda install -y -c conda-forge -c https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/channel/ --file requirements.txt
  - conda install -y -c conda-forge pytest
  - pip install .
  script:
  - pytest fsl_mrs/tests

pages:
  image: python:3.7
  stage: doc
  script:
  - pip install -U sphinx sphinx_rtd_theme
  - sphinx-build -b html ./docs/user_docs public
  artifacts:
    paths:
    - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
