image: python:3.7-slim-buster

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - python --version
  - pip install -r requirements.txt
  - pip install flake8 pytest

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  allow_failure: true
  script:
  - flake8 --max-line-length=120 fsl_mrs

pytest:
  stage: Test
  script:
  - pytest fsl_mrs/tests